import { getAccessToken } from "./auth";
import type { Playlist, Track } from "../types";

const API = "https://api.spotify.com/v1";

async function fetchWithRetry(
  url: string,
  init: RequestInit,
  attempt = 0,
): Promise<Response> {
  const response = await fetch(url, init);

  if (response.status === 429 && attempt < 3) {
    const retryAfter = Number(response.headers.get("Retry-After")) || 1;
    await new Promise((resolve) => setTimeout(resolve, retryAfter * 1000));
    return fetchWithRetry(url, init, attempt + 1);
  }

  return response;
}

async function spotify<T>(path: string, init?: RequestInit): Promise<T> {
  const token = await getAccessToken();
  if (!token) throw new Error("Not authenticated");

  const response = await fetchWithRetry(API + path, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      ...(init?.headers || {}),
    },
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(`Spotify API ${response.status}: ${detail}`);
  }

  return response.status === 204
    ? (undefined as T)
    : response.json();
}

function toTrack(raw: any): Track | null {
  const track = raw?.track ?? raw?.item ?? raw;
  if (!track?.uri || track.type === "episode") return null;

  return {
    id: track.id,
    uri: track.uri,
    name: track.name,
    album: track.album?.name ?? "Unknown album",
    albumImage: track.album?.images?.[0]?.url,
    artists: (track.artists ?? []).map((artist: any) => ({
      id: artist.id ?? artist.name,
      name: artist.name,
    })),
  };
}

async function collectPages(path: string) {
  const items: any[] = [];
  let next: string | null = API + path;

  while (next) {
    const token = await getAccessToken();
    if (!token) throw new Error("Not authenticated");

    const response = await fetchWithRetry(next, {
      headers: { Authorization: `Bearer ${token}` },
    });

    if (!response.ok) {
      throw new Error(`Spotify API ${response.status}`);
    }

    const page = await response.json();
    items.push(...(page.items ?? []));
    next = page.next;
  }

  return items;
}

export async function getMe() {
  return spotify<{ id: string; display_name: string }>("/me");
}

export async function getPlaylists(): Promise<Playlist[]> {
  const items = await collectPages("/me/playlists?limit=50");

  return items.map((playlist: any) => ({
    id: playlist.id,
    name: playlist.name,
    image: playlist.images?.[0]?.url,
    total: playlist.items?.total ?? playlist.tracks?.total ?? 0,
  }));
}

export async function getPlaylistTracks(id: string): Promise<Track[]> {
  const items = await collectPages(`/playlists/${id}/items?limit=100`);
  return items.map(toTrack).filter(Boolean) as Track[];
}

export async function getRecentTracks(): Promise<Track[]> {
  try {
    const data = await spotify<{ items: any[] }>(
      "/me/player/recently-played?limit=50",
    );
    return data.items.map(toTrack).filter(Boolean) as Track[];
  } catch {
    return [];
  }
}

export async function exportSequence(name: string, tracks: Track[]) {
  const me = await getMe();

  const playlist = await spotify<{
    id: string;
    external_urls: { spotify: string };
  }>(`/users/${me.id}/playlists`, {
    method: "POST",
    body: JSON.stringify({
      name,
      public: false,
      description:
        "Generated by Unshuffle: a user-controlled sequencing engine.",
    }),
  });

  for (let i = 0; i < tracks.length; i += 100) {
    await spotify(`/playlists/${playlist.id}/items`, {
      method: "POST",
      body: JSON.stringify({
        uris: tracks.slice(i, i + 100).map((track) => track.uri),
      }),
    });
  }

  return playlist.external_urls.spotify;
}
